name: bukizz_retailer
description: "Bukizz Retailer App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  responsive_sizer: ^3.3.0+1
  url_launcher: ^6.2.5
  file_picker: ^6.1.1
  firebase_auth: ^4.15.3
  firebase_core: ^2.25.5
  firebase_storage: ^11.6.7
  permission_handler: ^11.3.0
  image_picker: ^1.0.7
  crypto: ^3.0.3
  cloud_firestore: ^4.15.6
  firebase_database: ^10.4.7
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  dots_indicator: ^3.0.0
  carousel_slider: ^4.2.1
  geocoding: ^2.2.0
  geolocator: ^11.0.0
  uuid: ^4.3.3
  firebase_messaging: ^14.7.17
  flutter_local_notifications: ^16.3.2
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.0
  email_auth: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito/Nunito-Regular.ttf
        - asset: fonts/Nunito/Nunito-Bold.ttf
        - asset: fonts/Nunito/Nunito-Italic.ttf
        - asset: fonts/Nunito/Nunito-BoldItalic.ttf


  assets:
    - assets/